### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by avisaxena33** [PatrickAlphaC/nft-mix#45]
I'm on the part where we run the deploy script. Is 0.01 ETH not enough? I'm using a test wallet so I don't have much ETH on there.

<img width="950" alt="Screen Shot 2021-10-03 at 10 35 08 AM" src="https://user-images.githubusercontent.com/13755053/135761103-15e2e0ed-e264-47af-a387-84a4ab0ba370.png">

**Comment by EnricoBeltramo** [comment]
The coin needed in the test are LINK and not ETH because you are working on testnet Rinkeby (see begin of tutorial how to acquire them: https://www.freecodecamp.org/news/how-to-make-an-nft-and-render-on-opensea-marketplace/amp/), 
Anyway, either I have 40 LINK in my wallet, I have same issue. How much coins are needed for creation of the NFT?

**Comment by avisaxena33** [comment]
Ok I'm just an idiot newbie at this apparently. Idk why I thought we needed actual ETH ... I just added 20 LINK and one request worth of RETH and was able to run the deploy script ....

**Comment by EnricoBeltramo** [comment]
Good, In my case don't work, it still says insufficient funds for gas * price + value either I have 30 LINK in wallet, I don't know why

**Comment by PatrickAlphaC** [comment]
Do you have testnet rinkeby ETH @EnricoBeltramo?
