### ISSUE TITLE
Could not find files for given patterns when deploying contract

### ISSUE THREAD

**Issue by Negaunee0024** [PatrickAlphaC/nft-mix#74]
I get the same warning when I try to deploy a simple or advanced contract.  The contract still deploys, but there is always an error.  Here is the "problem" highlighted.  Thanks for your time. 
![image](https://user-images.githubusercontent.com/96413524/147037280-9d794803-4526-48c2-b69e-b5fc3f2f679f.png)

**Comment by PatrickAlphaC** [comment]
You can ignore that.

This is because you installed brownie with `pipx` (which is correct), but python doesn't see it in it's list of packages. You could install it with `pip` to make it go away, ignore it, or look at this: https://ethereum.stackexchange.com/questions/114841/failed-brownie-import-when-running-scripts/114857
